name: Auto Video Short

on:
  push:
    branches:
      - Production
  pull_request:
    branches:
      - Production

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AUDIO_NAME: "audio.mp3"
      VIDEO_NAME: "video.mp4"
      FINAL_VIDEO: "final_video.mp4"
      VIDEOURL: ${{ secrets.VIDEOURL }}
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python main.py

    - name: Commit output files
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add output/*
        git commit -m "Add generated video files"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }} 
