name: Auto Video Short

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AUDIO_NAME: "audio.mp3"
      VIDEO_NAME: "video.mp4"
      FINAL_VIDEO: "final_video.mp4"
      VIDEOURL: ${{ secrets.VIDEOURL }}
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python main.py

    - name: Upload video artifact
      uses: actions/upload-artifact@v3
      with:
        name: video-file
        path: output/
